name: Create Static Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  export-notebooks-and-build-static-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build static pages from content
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
