name: Create Static Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  export-notebooks-and-build-static-pages:
    runs-on: ubuntu-latest
    env:
      BASE_URL: /ai-centar-lipik
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt

      - name: Build static pages from content
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '_build/html/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
