name: Validate Jupyter Notebooks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - datasets/**
      - notebooks/**
      - requirements.txt

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Validate notebooks
        run: npm run validate
