name: Validate Jupyter Notebooks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - datasets/**
      - content/**
      - requirements.txt

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest
    env:
      BASE_URL: /ai-centar-lipik
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt

      - name: Validate content
        run: npm run build
